### ISSUE TITLE
Nelson Macario Martínez Hernández, 1AS, 24620235

### ISSUE THREAD

**Issue by Nelson295281** [SistemasTecTlaxiaco/infografia-Nelson295281#1]
[Nelson Macario Martínez Hernández, 1AS, N° 24620235.pdf](https://github.com/user-attachments/files/16735416/Nelson.Macario.Martinez.Hernandez.1AS.N.24620235.pdf)

**Comment by Johnc-byte** [comment]
redacción y ortografía : 14/14
exposición de ideas centrales : 16/16
organización de ideas centrales : 14/14
uso de imágenes y colores : 14/14
presentación visual : 14/14
referencias : 12/14
presentación : 14/14
calificación final : 19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
